#!/usr/bin/env python3
"""
replay_all.py -- r23 single reproducible entry point (SOLUTION-CONTRACT.md
section 9, item 2). Staged by C6-F3 (worker c6-f3, route F3, Cycle 6 of the
r23 delete-retag actual-tree DRE); the controller installs the frozen copy
at control/replay_all.py at the terminal gate.

WHAT THIS REPRODUCES (from sealed evidence, independently recomputed here,
never merely copy-pasted): the order-91 aggregate; the order-16 witness T16;
the CB(8,92) whole row (S / g_arm / g_u at the C4/C5 registrar receipt
figures); a 280-instance BRIDGE-identity sample (Stage-0 check E's own
seeded construction, seed=993); the C5-F3 path/star family spot-check
battery. Plus a PLANTED MUTATION control (duty 16: every certification
receipt must be able to fail) and an expected-value manifest with SHA-256s.

Evaluator is written directly from SEMANTIC-CONTRACT.md section 2/3 text
(i_k, Delta_k, x(T), a_v, b_v, B_{s_v}, F_p(T), S(T,p); BRIDGE-1/2). Family
generators (path/star/K13/hub_satellite_family/build_CB) reproduce the
STRUCTURAL descriptions on record (SOLUTION-CONTRACT.md section 6; C4/C5
`families.py`), not re-derived from scratch -- genuineness here is the
independent recomputation path and the falsifiable planted-mutation control,
per duty 16. T16's tree is the fixed, on-record design
(`cycles/cycle-4/stage3/routes/U4/evidence/rows/T16_p7.json`,
row_id T16_p7, source "designed:C3-ledger-T5-07"): its edge list is quoted
literally below with that citation, not regenerated by any formula (T16 is
a specific hand-designed witness, not a parametrized family).

DUTY-14/15 (run-root and --out discipline, mandatory, never an exemption):
  - The run root is read ONLY from the R23_RUN_ROOT environment variable.
    UNSET or unresolvable (does not exist / not a directory) is a REFUSE
    (exit 2), never a silent fallback and never path arithmetic from
    __file__ or cwd.
  - --root is REQUIRED on the command line and MUST resolve (realpath) to
    the identical path as R23_RUN_ROOT; a mismatch is a REFUSE (exit 2).
  - --out is REQUIRED (the no-`--out` idiom is FORBIDDEN). The resolved
    output directory MUST lie inside the run root AND MUST NOT lie inside
    a sealed subtree: control/, sources/, proposed/, or any
    cycles/cycle-1/ .. cycles/cycle-5/ (predecessor, sealed cycles).
    cycles/cycle-6/** and scratchpad/** (anywhere under the run root) are
    the only writable regions for this instrument. Violations REFUSE
    (exit 2).
  - Every REFUSE prints one `REFUSE: <reason>` line to stderr and exits
    with a nonzero, stated code (2). Both refusal paths are reachable and
    are demonstrated by an executed transcript shipped alongside this
    script's evidence (duty 14).

Stdlib only. Deterministic: the 280-instance sample uses Python's `random`
seeded at 993 -- IDENTICAL to control/stage0_audit_verification.py's own
check-E seeding -- so the instance SET (not merely the count) reproduces.
No wall-clock value is read, computed, or printed anywhere in this file.
"""
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import os
import random
import sys
from math import comb

# ---------------------------------------------------------------------------
# duty-14/15: run-root and --out resolution
# ---------------------------------------------------------------------------

SEALED_SUBTREES = ("control", "sources", "proposed") + tuple(
    f"cycles/cycle-{i}" for i in range(1, 6)
)


def refuse(reason: str, code: int = 2) -> None:
    sys.stderr.write(f"REFUSE: {reason}\n")
    sys.exit(code)


def resolve_root(cli_root: str | None) -> str:
    env_root = os.environ.get("R23_RUN_ROOT")
    if not env_root:
        refuse("R23_RUN_ROOT is unset. This instrument never derives the run "
               "root from __file__ or the current directory. Set "
               "R23_RUN_ROOT and re-run.")
    real_env = os.path.realpath(env_root)
    if not os.path.isdir(real_env):
        refuse(f"R23_RUN_ROOT ({env_root!r} -> {real_env!r}) does not resolve "
               "to an existing directory.")
    if not cli_root:
        refuse("--root is required (explicit, never implicit). Pass "
               "--root \"$R23_RUN_ROOT\".")
    real_cli = os.path.realpath(cli_root)
    if real_cli != real_env:
        refuse(f"--root ({cli_root!r} -> {real_cli!r}) does not match "
               f"R23_RUN_ROOT ({env_root!r} -> {real_env!r}). The two must "
               "agree exactly; this instrument does not silently prefer "
               "one over the other.")
    return real_env


def resolve_out(cli_out: str | None, root: str) -> str:
    if not cli_out:
        refuse("--out is required. The no-`--out` idiom is FORBIDDEN "
               "(standing duty 15).")
    real_out = os.path.realpath(cli_out)
    real_root = os.path.realpath(root)
    try:
        rel = os.path.relpath(real_out, real_root)
    except ValueError:
        rel = None
    if rel is None or rel == os.pardir or rel.startswith(os.pardir + os.sep):
        refuse(f"--out ({cli_out!r} -> {real_out!r}) resolves outside the "
               f"run root ({real_root!r}).")
    rel_posix = rel.replace(os.sep, "/")
    for sealed in SEALED_SUBTREES:
        if rel_posix == sealed or rel_posix.startswith(sealed + "/"):
            refuse(f"--out ({cli_out!r} -> resolved run-root-relative path "
                   f"{rel_posix!r}) lies inside the sealed subtree "
                   f"{sealed!r}. Writable regions for this instrument are "
                   "only cycles/cycle-6/** and scratchpad/** under the run "
                   "root.")
    os.makedirs(real_out, exist_ok=True)
    return real_out


# ---------------------------------------------------------------------------
# evaluator (SEMANTIC-CONTRACT.md section 2: i_k, Delta_k, x(T), S(T,p))
# ---------------------------------------------------------------------------

def poly_add(a, b):
    n = max(len(a), len(b))
    out = [0] * n
    for i, x in enumerate(a):
        out[i] += x
    for i, x in enumerate(b):
        out[i] += x
    return out


def poly_mul(a, b):
    if not a or not b:
        return [0]
    out = [0] * (len(a) + len(b) - 1)
    for i, ai in enumerate(a):
        if not ai:
            continue
        for j, bj in enumerate(b):
            if bj:
                out[i + j] += ai * bj
    return out


def poly_shift(a):
    return [0] + list(a)


def coef(poly, k):
    return poly[k] if 0 <= k < len(poly) else 0


def delta(poly, k):
    return coef(poly, k + 1) - coef(poly, k)


def first_strict_descent(poly, guard=None):
    k = 0
    limit = guard if guard is not None else (len(poly) + 3)
    while True:
        if delta(poly, k) < 0:
            return k
        k += 1
        if k > limit:
            raise RuntimeError("no strict descent found within guard bound")


def adjacency(n, edges):
    adj = [set() for _ in range(n)]
    for a, b in edges:
        adj[a].add(b)
        adj[b].add(a)
    return adj


def induced_components(adj, vertices):
    vertices = set(vertices)
    seen, comps = set(), []
    for start in vertices:
        if start in seen:
            continue
        comp, stack = set(), [start]
        seen.add(start)
        while stack:
            u = stack.pop()
            comp.add(u)
            for w in adj[u]:
                if w in vertices and w not in seen:
                    seen.add(w)
                    stack.append(w)
        comps.append(comp)
    return comps


def dp_indep_poly_tree(adj, vertices):
    vertices = list(vertices)
    if not vertices:
        return [1]
    root = min(vertices)
    vset = set(vertices)
    parent = {root: None}
    order = [root]
    stack = [root]
    visited = {root}
    while stack:
        u = stack.pop()
        for w in adj[u]:
            if w in vset and w not in visited:
                visited.add(w)
                parent[w] = u
                order.append(w)
                stack.append(w)
    assert len(order) == len(vertices), "induced set is not one tree component"
    children = {v: [] for v in vertices}
    for v in order[1:]:
        children[parent[v]].append(v)
    A, B = {}, {}
    for v in reversed(order):
        a_poly, b_poly = [1], [1]
        for c in children[v]:
            a_poly = poly_mul(a_poly, poly_add(A[c], B[c]))
            b_poly = poly_mul(b_poly, A[c])
        A[v] = a_poly
        B[v] = poly_shift(b_poly)
    return poly_add(A[root], B[root])


def dp_indep_poly(adj, vertices):
    poly = [1]
    for comp in induced_components(adj, vertices):
        poly = poly_mul(poly, dp_indep_poly_tree(adj, comp))
    return poly


BRUTE_MAX_N = 22  # 2^22 subset-scan ceiling for the independent cross-check


def brute_indep_poly(adj, vertices):
    verts = sorted(vertices)
    m = len(verts)
    if m > BRUTE_MAX_N:
        return None
    idx = {v: i for i, v in enumerate(verts)}
    nbmask = [0] * m
    for v in verts:
        mv = 0
        for w in adj[v]:
            if w in idx:
                mv |= (1 << idx[w])
        nbmask[idx[v]] = mv
    counts = {}
    for mask in range(1 << m):
        bits = [i for i in range(m) if (mask >> i) & 1]
        if any(nbmask[i] & mask for i in bits):
            continue
        k = len(bits)
        counts[k] = counts.get(k, 0) + 1
    if not counts:
        return [1]
    top = max(counts)
    return [counts.get(k, 0) for k in range(top + 1)]


def leaves_and_supports(adj, n):
    return [(v, next(iter(adj[v]))) for v in range(n) if len(adj[v]) == 1]


def closed_nbhd(adj, v):
    return {v} | set(adj[v])


def evaluate_row(n, edges, p, cross_check=True):
    adj = adjacency(n, edges)
    full = set(range(n))
    polyT = dp_indep_poly(adj, full)
    xT = first_strict_descent(polyT)
    governed = p >= xT + 2

    F, S, S_brute = [], 0, 0
    brute_ok = bool(cross_check)
    leaf_rows = []
    for v, s_v in leaves_and_supports(adj, n):
        Tv = full - {v}
        a_v = delta(dp_indep_poly(adj, Tv), p)
        Hv = full - {v, s_v}
        b_v = delta(dp_indep_poly(adj, Hv), p - 1)
        Nsv = full - closed_nbhd(adj, s_v)
        B_sv = delta(dp_indep_poly(adj, Nsv), p - 1)
        g_v = b_v - B_sv
        favorable = a_v < 0
        if favorable:
            F.append(v)
            S += g_v
        if cross_check and brute_ok:
            b_Tv, b_Hv, b_Nsv = (brute_indep_poly(adj, Tv),
                                  brute_indep_poly(adj, Hv),
                                  brute_indep_poly(adj, Nsv))
            if b_Tv is None or b_Hv is None or b_Nsv is None:
                brute_ok = False
            else:
                a_v_b, b_v_b, B_sv_b = (delta(b_Tv, p), delta(b_Hv, p - 1),
                                         delta(b_Nsv, p - 1))
                if (a_v_b, b_v_b, B_sv_b) != (a_v, b_v, B_sv):
                    raise AssertionError(
                        f"cross-check mismatch at leaf {v}: "
                        f"DP=({a_v},{b_v},{B_sv}) brute=({a_v_b},{b_v_b},{B_sv_b})")
                if favorable:
                    S_brute += b_v_b - B_sv_b
        leaf_rows.append(dict(v=v, s_v=s_v, a_v=a_v, b_v=b_v, B_sv=B_sv,
                               g_v=g_v, favorable=favorable))

    return dict(n=n, x=xT, p=p, governed=governed, leaf_rows=leaf_rows, F=F,
                num_favorable=len(F), S=S,
                S_brute=(S_brute if brute_ok else None),
                cross_check_agrees=(brute_ok and S_brute == S) if brute_ok else None)


def bridge1_counts(n, edges, v, s_v, r):
    """|C_r(v)| via BRIDGE-1: i_r(H_v) - i_r(T - N[s_v])."""
    adj = adjacency(n, edges)
    full = set(range(n))
    Hv = full - {v, s_v}
    Nsv = full - closed_nbhd(adj, s_v)
    return coef(dp_indep_poly(adj, Hv), r) - coef(dp_indep_poly(adj, Nsv), r)


# ---------------------------------------------------------------------------
# planted-mutation evaluator (open neighborhood instead of closed) -- duty 16
# ---------------------------------------------------------------------------

def evaluate_row_mutant_open_nbhd(n, edges, p):
    adj = adjacency(n, edges)
    full = set(range(n))
    xT = first_strict_descent(dp_indep_poly(adj, full))
    F, S = [], 0
    for v, s_v in leaves_and_supports(adj, n):
        Tv = full - {v}
        a_v = delta(dp_indep_poly(adj, Tv), p)
        Hv = full - {v, s_v}
        b_v = delta(dp_indep_poly(adj, Hv), p - 1)
        Nsv_open = full - set(adj[s_v])  # BUG: omits s_v itself (open, not closed)
        B_sv = delta(dp_indep_poly(adj, Nsv_open), p - 1)
        if a_v < 0:
            F.append(v)
            S += (b_v - B_sv)
    return xT, len(F), S


# ---------------------------------------------------------------------------
# family generators (structural descriptions on record; see module docstring)
# ---------------------------------------------------------------------------

def path_tree(n):
    return n, [(i, i + 1) for i in range(n - 1)]


def star_tree(n):
    return n, [(0, i) for i in range(1, n)]


def K13():
    return star_tree(4)


def hub_satellite_family(m):
    """Order-91 control family (SOLUTION-CONTRACT.md section 6; m=22 -> n=91):
    hub 0; arm 0-1(s)-2(v); m satellites c_i each with 3 pendant leaves, all
    attached to hub 0. n(m) = 3 + 4*m."""
    edges = [(0, 1), (1, 2)]
    nid = 3
    for _ in range(m):
        c = nid
        nid += 1
        edges.append((0, c))
        for _ in range(3):
            edges.append((c, nid))
            nid += 1
    return nid, edges


def build_CB(j, k):
    """hub 0; arm 0-1(s)-2(v); k chokes; each choke j supports; each support
    exactly one leaf. n = 3 + k + 2*j*k.
    Returns (n, edges, v, s, hub)."""
    hub, s, v = 0, 1, 2
    edges = [(hub, s), (s, v)]
    nxt = 3
    for _ in range(k):
        z = nxt
        nxt += 1
        edges.append((hub, z))
        for _ in range(j):
            y, u = nxt, nxt + 1
            nxt += 2
            edges += [(z, y), (y, u)]
    return nxt, edges, v, s, hub


# T16: fixed, hand-designed witness on record (NOT a parametrized family).
# Source: cycles/cycle-4/stage3/routes/U4/evidence/rows/T16_p7.json
#   row_id "T16_p7", source "designed:C3-ledger-T5-07", edges_tree verbatim.
T16_N = 16
T16_EDGES = [(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (1, 7), (1, 8),
             (1, 9), (2, 10), (2, 11), (2, 12), (7, 13), (8, 14), (9, 15)]
T16_P = 7


def pruefer_decode(n, seq):
    degree = [1] * n
    for x in seq:
        degree[x] += 1
    edges = []
    import heapq
    leaves = [i for i in range(n) if degree[i] == 1]
    heapq.heapify(leaves)
    for x in seq:
        leaf = heapq.heappop(leaves)
        edges.append((leaf, x))
        degree[leaf] -= 1
        degree[x] -= 1
        if degree[x] == 1:
            heapq.heappush(leaves, x)
    remaining = [i for i in range(n) if degree[i] == 1]
    edges.append((remaining[0], remaining[1]))
    return edges


def pruefer_exhaustive(n):
    """All labeled trees on n vertices via exhaustive Pruefer sequences."""
    if n < 2:
        return
    for seq in itertools.product(range(n), repeat=n - 2):
        yield pruefer_decode(n, list(seq))


# ---------------------------------------------------------------------------
# 280-instance BRIDGE-identity sample -- reproduces
# control/stage0_audit_verification.py check E EXACTLY (same seed=993,
# same n range 8..12, same exhaustive-vs-25-cap / 30-random construction),
# so the instance SET (not merely the count) reproduces.
# ---------------------------------------------------------------------------

def bridge_check_instance(n, edges, p):
    """Literal active-set enumeration vs the coefficient identity, plus
    |P| - |N| = S, on one (T, p) instance. Returns True/False/None
    (None = ungoverned, excluded from the sample)."""
    adj = adjacency(n, edges)
    xT = first_strict_descent(dp_indep_poly(adj, set(range(n))))
    if p < xT + 2:
        return None
    es = set(map(frozenset, edges))

    def ind_sets(vertices, r):
        for S in itertools.combinations(vertices, r):
            if all(frozenset(e) - set(S) for e in es if frozenset(e) <= set(vertices)):
                yield S

    Ptot = Ntot = Sagg = 0
    ok = True
    for v in range(n):
        if len(adj[v]) != 1:
            continue
        s = next(iter(adj[v]))
        full = set(range(n))
        a_v = delta(dp_indep_poly(adj, full - {v}), p)
        if a_v >= 0:
            continue
        W = [w for w in adj[s] if w != v]
        Hverts = [u for u in range(n) if u not in (v, s)]
        Cp = sum(1 for A in ind_sets(Hverts, p) if set(A) & set(W))
        Cp1 = sum(1 for A in ind_sets(Hverts, p - 1) if set(A) & set(W))
        b_v = delta(dp_indep_poly(adj, full - {v, s}), p - 1)
        B_s = delta(dp_indep_poly(adj, full - closed_nbhd(adj, s)), p - 1)
        g_v = b_v - B_s
        if Cp - Cp1 != g_v:
            ok = False
        Ptot += Cp
        Ntot += Cp1
        Sagg += g_v
    return ok and (Ptot - Ntot == Sagg)


def run_bridge_sample():
    checks = []
    rng = random.Random(993)
    for n in range(8, 13):
        if n <= 9:
            # matches control/stage0_audit_verification.py check E exactly:
            # cnt is incremented BEFORE the cap test, so exactly the first 25
            # trees are appended (the 26th increments cnt to 26 and breaks
            # without being appended or processed).
            trees, cnt = [], 0
            for edges in pruefer_exhaustive(n):
                cnt += 1
                if cnt > 25:
                    break
                trees.append(edges)
        else:
            trees = []
            for _ in range(30):
                seq = [rng.randrange(n) for _ in range(n - 2)]
                trees.append(pruefer_decode(n, seq))
        for edges in trees:
            adj = adjacency(n, edges)
            xT = first_strict_descent(dp_indep_poly(adj, set(range(n))))
            for p in range(xT + 2, xT + 4):
                r = bridge_check_instance(n, edges, p)
                if r is not None:
                    checks.append(r)
    return dict(instances=len(checks), all_hold=all(checks))


# ---------------------------------------------------------------------------
# expected values (pinned BEFORE this instrument runs, from sealed evidence;
# a mismatch below is a real, reportable failure -- never a null control)
# ---------------------------------------------------------------------------

EXPECTED = {
    "order91_x": 32,
    "order91_favorable": 67,
    "order91_S": -498754180547001418536,
    "T16_x": 5,
    "T16_p": 7,
    "T16_num_favorable": 10,
    "T16_S": -1690,
    "T16_P": 2255,
    "T16_N": 3945,
    "CB892_x": 490,
    "CB892_p": 492,
    "CB892_S_digits": 351,
    "CB892_S_prefix19": "-748810430710227858",
    "CB892_S_suffix6": "557120",
    "CB892_g_arm_digits": 347,
    "CB892_g_arm_sign": "positive",
    "CB892_g_u_digits": 349,
    "CB892_g_u_sign": "negative",
    "CB892_g_u_head": "-10175303027613826582334935008",
    "CB892_g_u_tail": "91918151536775447420",
    "CB892_Cp_Cp1_digits": 350,
    "bridge_sample_instances": 280,
    "bridge_sample_all_hold": True,
}

EXPECTED_SOURCES = {
    "order91_*": "SOLUTION-CONTRACT.md section 6; control/STAGE0-AUDIT-VERIFICATION-RESULTS.json (D_order91); "
                  "cycles/cycle-4/stage3/routes/U4/evidence/o91/o91-row.json",
    "T16_*": "cycles/cycle-4/stage3/routes/U4/evidence/rows/T16_p7.json (row_id T16_p7); HANDOFF-SPINE.md sec.5",
    "CB892_x/p/S_*": "cycles/cycle-5/stage3/routes/F3/evidence/code/cb892_full_row_reproduction.py "
                      "(EXPECTED_X/P/DIGITS/PREFIX/SUFFIX); HANDOFF-SPINE.md line 531",
    "CB892_g_arm_*/g_u_*": "control/c5-registrar-gu-receipt.json (duty-22 figure of record)",
    "CB892_Cp_Cp1_digits": "control/c4-registrar-w4-witness-receipt.json (a_v_digits)",
    "bridge_sample_*": "control/STAGE0-AUDIT-VERIFICATION-RESULTS.json (E_bridge_identity); "
                        "control/stage0_audit_verification.py (check E, seed=993)",
}


def canon(value) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode()


def sha256_of(value) -> str:
    return hashlib.sha256(canon(value)).hexdigest()


def build_manifest():
    manifest = {
        "expected": EXPECTED,
        "expected_sha256": {k: sha256_of(v) for k, v in EXPECTED.items()},
        "sources": EXPECTED_SOURCES,
    }
    preimage = json.dumps(manifest["expected_sha256"], ensure_ascii=False,
                           separators=(",", ":"), sort_keys=True)
    manifest["expected_sha256_manifest_seal"] = hashlib.sha256(
        preimage.encode()).hexdigest()
    return manifest


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", help="run root; must equal $R23_RUN_ROOT exactly")
    ap.add_argument("--out", help="output directory (required; must be in-root, unsealed)")
    args = ap.parse_args()

    root = resolve_root(args.root)
    out = resolve_out(args.out, root)

    report = {"checks": [], "fail": [], "planted_mutation_fires": []}

    def check(name, actual, expected):
        ok = (actual == expected)
        entry = dict(name=name, actual=actual, expected=expected, ok=ok)
        report["checks"].append(entry)
        if not ok:
            report["fail"].append(entry)
        return ok

    # -- order-91 aggregate ---------------------------------------------
    n91, e91 = hub_satellite_family(22)
    row91 = evaluate_row(n91, e91, 34, cross_check=True)
    check("order91_n", n91, 91)
    check("order91_x", row91["x"], EXPECTED["order91_x"])
    check("order91_favorable", row91["num_favorable"], EXPECTED["order91_favorable"])
    check("order91_S", row91["S"], EXPECTED["order91_S"])
    check("order91_S_brute_declines_by_design", row91["S_brute"], None)

    # -- T16 witness (order-16) ------------------------------------------
    rowT16 = evaluate_row(T16_N, T16_EDGES, T16_P, cross_check=True)
    check("T16_x", rowT16["x"], EXPECTED["T16_x"])
    check("T16_num_favorable", rowT16["num_favorable"], EXPECTED["T16_num_favorable"])
    check("T16_S", rowT16["S"], EXPECTED["T16_S"])
    check("T16_cross_check_agrees", rowT16["cross_check_agrees"], True)
    # P = sum |C_p(v)|, N = sum |C_{p-1}(v)| over favorable v, via BRIDGE-1
    P16 = sum(bridge1_counts(T16_N, T16_EDGES, v, s_v, T16_P)
              for v, s_v in leaves_and_supports(adjacency(T16_N, T16_EDGES), T16_N)
              if delta(dp_indep_poly(adjacency(T16_N, T16_EDGES), set(range(T16_N)) - {v}), T16_P) < 0)
    N16 = sum(bridge1_counts(T16_N, T16_EDGES, v, s_v, T16_P - 1)
              for v, s_v in leaves_and_supports(adjacency(T16_N, T16_EDGES), T16_N)
              if delta(dp_indep_poly(adjacency(T16_N, T16_EDGES), set(range(T16_N)) - {v}), T16_P) < 0)
    check("T16_P_via_BRIDGE1", P16, EXPECTED["T16_P"])
    check("T16_N_via_BRIDGE1", N16, EXPECTED["T16_N"])
    check("T16_P_minus_N_eq_S", P16 - N16, EXPECTED["T16_S"])

    # -- CB(8,92) whole row: S, g_arm, g_u, and the BRIDGE-1 cross-check --
    nCB, eCB, vCB, sCB, hubCB = build_CB(8, 92)
    check("CB892_n", nCB, 1567)
    rowCB = evaluate_row(nCB, eCB, 492, cross_check=False)
    check("CB892_x", rowCB["x"], EXPECTED["CB892_x"])
    S = rowCB["S"]
    S_str = str(S)
    check("CB892_S_digits", len(S_str.lstrip("-")), EXPECTED["CB892_S_digits"])
    check("CB892_S_startswith_prefix19", S_str.startswith(EXPECTED["CB892_S_prefix19"]), True)
    check("CB892_S_suffix6", S_str[-6:], EXPECTED["CB892_S_suffix6"])

    # g_arm: independent combinatorial path (math.comb), not the tree DP.
    g_arm = comb(736, 491) * (2 ** 491) - comb(736, 490) * (2 ** 490)
    g_arm_str = str(g_arm)
    check("CB892_g_arm_digits", len(g_arm_str.lstrip("-")), EXPECTED["CB892_g_arm_digits"])
    check("CB892_g_arm_sign", "positive" if g_arm > 0 else "negative", EXPECTED["CB892_g_arm_sign"])

    # g_arm cross-checked a THIRD way: BRIDGE-1 on the arm leaf directly
    # from the tree DP (|C_p(arm)| - |C_{p-1}(arm)|), independent of the
    # comb() closed form above.
    Cp_arm = bridge1_counts(nCB, eCB, vCB, sCB, 492)
    Cp1_arm = bridge1_counts(nCB, eCB, vCB, sCB, 491)
    g_arm_dp = Cp_arm - Cp1_arm
    check("CB892_g_arm_DP_matches_comb_closed_form", g_arm_dp, g_arm)
    check("CB892_Cp_arm_digits", len(str(Cp_arm).lstrip("-")), EXPECTED["CB892_Cp_Cp1_digits"])
    check("CB892_Cp1_arm_digits", len(str(Cp1_arm).lstrip("-")), EXPECTED["CB892_Cp_Cp1_digits"])

    # g_u via the adjudicated identity S = g_arm + 736*g_u (registrar
    # method of record, control/c5-registrar-gu-receipt.json); NEVER
    # re-litigated, only reproduced.
    check("CB892_S_minus_g_arm_divisible_by_736", (S - g_arm) % 736, 0)
    g_u = (S - g_arm) // 736
    g_u_str = str(g_u)
    check("CB892_g_u_digits", len(g_u_str.lstrip("-")), EXPECTED["CB892_g_u_digits"])
    check("CB892_g_u_sign", "positive" if g_u > 0 else "negative", EXPECTED["CB892_g_u_sign"])
    check("CB892_g_u_head", g_u_str[:len(EXPECTED["CB892_g_u_head"])], EXPECTED["CB892_g_u_head"])
    check("CB892_g_u_tail", g_u_str[-len(EXPECTED["CB892_g_u_tail"]):], EXPECTED["CB892_g_u_tail"])
    check("CB892_identity_S_eq_g_arm_plus_736_g_u", g_arm + 736 * g_u, S)

    # -- 280-instance BRIDGE-identity sample (Stage-0 check E, reproduced) -
    bridge = run_bridge_sample()
    check("bridge_sample_instances", bridge["instances"], EXPECTED["bridge_sample_instances"])
    check("bridge_sample_all_hold", bridge["all_hold"], EXPECTED["bridge_sample_all_hold"])

    # -- C5-F3 path/star family spot checks (control_battery.py, sealed) --
    for n in (3, 4, 5, 8, 12):
        tn, edges = path_tree(n)
        adj = adjacency(tn, edges)
        x = first_strict_descent(dp_indep_poly(adj, set(range(tn))))
        row = evaluate_row(tn, edges, x + 2, cross_check=True)
        check(f"path(n={n})_governed_cross_check_agrees", row["cross_check_agrees"], True)
    for n in (3, 4, 5, 8, 12):
        tn, edges = star_tree(n)
        adj = adjacency(tn, edges)
        x = first_strict_descent(dp_indep_poly(adj, set(range(tn))))
        row = evaluate_row(tn, edges, x + 2, cross_check=True)
        check(f"star(n={n})_governed_cross_check_agrees", row["cross_check_agrees"], True)
        check(f"star(n={n})_shared_support_leaf_count", len(row["leaf_rows"]), n - 1)

    # -- PLANTED MUTATION CONTROL (duty 16: must actually fire) -----------
    xm, favm, Sm = evaluate_row_mutant_open_nbhd(n91, e91, 34)
    fired = not (xm == EXPECTED["order91_x"] and favm == EXPECTED["order91_favorable"]
                 and Sm == EXPECTED["order91_S"])
    report["planted_mutation_fires"].append(dict(
        name="open-neighborhood bug vs order-91 pin (B_{s_v} uses N(s_v) "
             "instead of the closed neighborhood N[s_v])",
        detected=fired, mutant_S=Sm, expected_S=EXPECTED["order91_S"]))
    if not fired:
        report["fail"].append(dict(name="PLANTED_MUTATION_DID_NOT_FIRE",
                                    actual=Sm, expected="!= " + str(EXPECTED["order91_S"])))

    # -- manifest + summary -------------------------------------------------
    manifest = build_manifest()
    report["expected_value_manifest"] = manifest
    report["summary"] = dict(
        total_checks=len(report["checks"]),
        passed=len(report["checks"]) - len(report["fail"]),
        failed=len(report["fail"]),
        planted_mutation_fired=fired,
        overall_pass=(len(report["fail"]) == 0 and fired),
    )

    out_path = os.path.join(out, "replay_report.json")
    with open(out_path, "w") as f:
        json.dump(report, f, indent=1, sort_keys=True)
    manifest_path = os.path.join(out, "EXPECTED-VALUES-MANIFEST.json")
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=1, sort_keys=True)

    print(json.dumps(report["summary"], indent=1, sort_keys=True))
    if report["fail"]:
        print("FAILURES:", json.dumps(report["fail"], indent=1, sort_keys=True))
        sys.exit(1)
    if not fired:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
