name = "c8U3Selector"
version = "0.1.0"
defaultTargets = ["C8U3Selector"]

[[lean_lib]]
name = "C8U3Selector"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "905b95818eb32af7874a58b427f50c1711a5e96c"
