import R12C2P

#check @conv_coeff
#check @conv_coeff_swap
#check @conv_coeff_swap_ext
#check @shiftBack_coeff
#check @succ_via_shift
#check @conv_coeff_pair
#check @Unimodal.zero
#check @sub_Kset
#check @sub_Kset'
#check @dn_eq
#check @Uw_nonneg
#check @Vw_nonneg
#check @UV_cross
#check @no_down_up
#check @step_chain
#check @step_chain'
#check @unimodal_of_no_down_up
#check @P1_NNSeq
#check @witnessA_not_PIS
#check @witnessA_ne_zero
#check @witnessA_not_TRS2
